<?php

/**
 * @todo
 *  - Pull the aq-specific functions out of .module and add it to it's own .inc file. 
 */

/**
 * Implements hook_menu.
 */
function mcoc_stats_menu() {
  $items['mcoc/stats/aq'] = array(
    'title' => 'BG2 AQ Stats', 
    'description' => 'Alliance quest stats',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('mcoc_stats_aq'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/mcoc_stats.aq.inc',
  );

  $items['mcoc/mass-upload-form'] = array(
    'title' => 'AQ Mass Upload Form', 
    'description' => 'Allows for uploading multiple bg and individual aq records.',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('mcoc_mass_upload_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/mcoc_stats.mass-upload-form.inc',
  );
  return $items;
}

/**
 * Get all of the individual AQ records.
 */
function mcoc_stats_get_records($type, $top_ten = FALSE, $range = 10) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $type);

  if($top_ten) {
    $query->fieldOrderBy('field_points', 'value', 'DESC')->range(0, $range);
  }

  $records = $query->execute();
  return $records['node'];
}

