<?php

/**
 * @todo
 *  - Pull the aq-specific functions out of .module and add it to it's own .inc file. 
 */

/**
 * Implements hook_menu.
 */
function mcoc_stats_menu() {
  $items['mcoc/stats/aq'] = array(
    'title' => 'BG2 AQ Stats', 
    'description' => 'Alliance quest stats',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('mcoc_stats_aq'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/mcoc_stats.aq.inc',
  );

  $items['mcoc/mass-upload-form'] = array(
    'title' => 'AQ Mass Upload Form', 
    'description' => 'Allows for uploading multiple bg and individual aq records.',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('mcoc_mass_upload_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Get all of the individual AQ records.
 */
function mcoc_stats_get_records($type, $top_ten = FALSE, $range = 10) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', $type);

  if($top_ten) {
    $query->fieldOrderBy('field_points', 'value', 'DESC')->range(0, $range);
  }

  $records = $query->execute();
  return $records['node'];
}

function mcoc_mass_upload_form($form, &$form_state) {
  // Attach our CSS       
  $form['#attached']['css'] = array(drupal_get_path('module', 'mcoc_stats') . '/css/mcoc_stats.mass-upload-aq.css');
  $num_members = 30;
  $members = array();
  $users = entity_load('user');
  // Load the users into an array.
  foreach($users as $user) {
    $members[$user->uid] = $user->name;
  }

  $form['day'] = array(
    '#type' => 'textfield',
    '#title' => 'Day #',
  );

  $form['map'] = array(
    '#type' => 'textfield',
    '#title' => 'Map #',
  );

  $form['date'] = array(
    '#type' => 'date_popup',
    '#timepicker' => 'timepicker',
    '#title' => "AQ Start Date",
    '#date_format' => 'm/d/Y',
  );

  $form['boss'] = array(
    '#type' => 'textfield',
    '#title' => 'Boss Defeated?',
  );

  $form['explored'] = array(
    '#type' => 'textfield',
    '#title' => 'Explored %',
  );

  $form['bg'] = array(
    '#type' => 'textfield',
    '#title' => 'BG #',
  );

  $form['row_wrapper'] = array(
    '#container' => TRUE,
    '#pre' => '<div class="mass-upload-form-container">',
    '#post' => '</div>',
  );

  for ($i=0; $i < $num_members; $i++) {

    $form['row_wrapper'][$i]['member'] = array(
      '#type' => 'select',
      '#title' => "Memeber $i",
      '#options' => $members,
    );
    
    
    $form['row_wrapper'][$i]['points'] = array(
      '#type' => 'textfield',
      '#title' => "Points",
    );

    $form['row_wrapper'][$i]['clearall'] = array(
      '#markup' => '<div class="clearall">&nbsp;</div>',
    );
  }

  return $form;
}